In [6]:
import pandas as pd
import numpy as np
# from dateinfer import infer

In [7]:
# Listing all data files
!ls ./large_files -al

total 314816
drwxrwxr-x 2 monk monk      4096 Aug  4 22:06 .
drwxrwxr-x 7 monk monk      4096 Sep 14 21:05 ..
-rw-rw-r-- 1 monk monk  52872856 Jul 18 14:18 archive.zip
-rw-rw-r-- 1 monk monk 257414189 Sep 21  2019 bottle.csv
-rw-rw-r-- 1 monk monk  12065734 Sep 21  2019 cast.csv

In [8]:
df =pd.read_csv("./large_files/cast.csv")
df.head()

/home/monk/Software/miniconda3/envs/dsmonk/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (40,41,44,45,46,47) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Cst_Cnt,Cruise_ID,Cruise,Cruz_Sta,DbSta_ID,Cast_ID,Sta_ID,Quarter,Sta_Code,Distance,...,Wave_Prd,Wind_Dir,Wind_Spd,Barometer,Dry_T,Wet_T,Wea,Cloud_Typ,Cloud_Amt,Visibility
0,1,1949-03-01-C-31CR,194903,19490305400560,5400560,19-4903CR-HY-060-0930-05400560,054.0 056.0,1,NST,NaN,...,NaN,23.0,18.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN
1,2,1949-03-01-C-31CR,194903,19490305200750,5200750,19-4903CR-HY-060-2112-05200750,052.0 075.0,1,NST,NaN,...,NaN,16.0,5.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN
2,3,1949-03-01-C-31CR,194903,19490305100850,5100850,19-4903CR-HY-061-0354-05100850,051.0 085.0,1,NST,NaN,...,NaN,23.0,5.0,NaN,NaN,NaN,6.0,NaN,NaN,NaN
3,4,1949-03-01-C-31CR,194903,19490305000950,5000950,19-4903CR-HY-061-1042-05000950,050.0 095.0,1,NST,NaN,...,NaN,18.0,8.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN
4,5,1949-03-01-C-31CR,194903,19490305001040,5001040,19-4903CR-HY-061-1706-05001040,050.0 104.0,1,NST,NaN,...,NaN,27.0,13.0,NaN,NaN,NaN,7.0,NaN,NaN,NaN

% floats: percentage of values that are float
% int: percentage of values that are whole numbers
% string: percentage of values that are strings
% unique string: number of unique string values / total number
% unique integers: number of unique integer values / total number
mean numerical value (non numerical values considered 0 for this)
std deviation of numerical values

In [ ]:

class Colu:
    def __init__(self,df, col, sorp):
        
        self.col=col
        self.data=np.array( list(df[col]) )
        self.sorp=sorp
        
        # Identify
        self.prediction="unknown"
        self.dtype="unknown"
        self.n=0
        no_of_unique=0,
        ratio=0,
    
        # Describe
        self.high=np.nan
        self.low=np.nan
        self.range=np.nan
        
        self.mean=np.nan
        self.median=np.nan
        self.mode=np.nan
        
        self.q1=np.nan
        self.q3=np.nan
        self.iqd=np.nan
        
        self.var=np.nan
        self.std=np.nan
        
        self.skewness=np.nan
        self.kurtosis=np.nan
        
        self.nofbins=np.nan
        
        
    def identify(self):
        self.no_of_unique=len(np.unique(self.data)) 
        self.n=len(self.data)
        self.ratio= float(self.no_of_unique/self.n) *100
        self.ratio=round(self.ratio,2)
        
        self.dtype=str(self.data.dtype)
       
        if "<U" in self.dtype:    
            if self.ratio <=10:
                self.prediction="category"
            try:
                pd.to_datetime(df[col])
                self.prediction="datetime"
            except:
                pass
            
        if "int" in self.dtype:
            if self.ratio <=10:
                self.prediction="int category"
            else:
                self.prediction="feature"
        
        if "float" in self.dtype:
            self.prediction="feature"
            
        
        if self.ratio==100:
            self.prediction="primary key"
    
    
        self.identify_dict={
            "col":self.col,
            "prediction":self.prediction,
            "dtype":self.dtype,
            "n":self.n,
            "no_of_unique":self.no_of_unique,
            "ratio":self.ratio,
        }
        
        return self.identify_dict
        
    def describe(self):
        
        self.identify()
        
        if ("int" in self.dtype) or ("float" in self.dtype):
            self.high=self.data.max()
            self.low=self.data.min()
            self.range=self.high-self.low

            from scipy import stats
            
            self.mean=self.data.mean()
            self.median=np.quantile(self.data, .5)
            self.mode=stats.mode(self.data)[0]
            
            self.q1=np.quantile(self.data, .25)
            self.q3=np.quantile(self.data, .75)
            self.iqd=self.q3-self.q1

            self.var=self.data.var()
            self.std=self.data.std()

            from scipy.stats import kurtosis
            from scipy.stats import skew

            self.skewness=skew(self.data)
            self.kurtosis=kurtosis(self.data)

            self.nofbins= np.round( 1+3.22*np.log10(self.n)+0.5 , 0 )

        self.describe_dict={
            "high":self.high,
            "low":self.low,
            "range":self.range,

            "mean":self.mean,
            "meadian":self.median,
            "mode":self.mode,

            "q1":self.q1,
            "q2":self.q3,
            "q3":self.iqd,

            "var":self.var,
            "std":self.std,

            "skewness":self.skewness,
            "kurtosis":self.kurtosis,

            "nofbins":self.nofbins,
            }

        return self.describe_dict
    
    def charting(self):
#         if ("int" in self.dtype) or ("float" in self.dtype):
#             mychart = Chart(data=self.data, kind='bar')
        pass
        
        
for col in df.columns:
    obj=Colu(df,col,"sample")
    obj.describe()
#     obj.charting()

In [ ]:
from bokeh.plotting import figure, output_file, show